name: Deploy to GitHub Pages

on:
  push:
    branches:
      - grupoA
      - grupoB
      - grupoC
      - teste1
      - teste2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Deploy grupoA
      if: github.ref == 'refs/heads/grupoA'
      run: |
        mkdir -p public/grupoA
        mv * public/grupoA/
        touch public/grupoA/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy grupoA to GitHub Pages"
        git push origin grupoA

    - name: Deploy grupoB
      if: github.ref == 'refs/heads/grupoB'
      run: |
        mkdir -p public/grupoB
        mv * public/grupoB/
        touch public/grupoB/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy grupoB to GitHub Pages"
        git push origin grupoB

    - name: Deploy grupoC
      if: github.ref == 'refs/heads/grupoC'
      run: |
        mkdir -p public/grupoC
        mv * public/grupoC/
        touch public/grupoC/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy grupoC to GitHub Pages"
        git push origin grupoC

    - name: Deploy teste1
      if: github.ref == 'refs/heads/teste1'
      run: |
        mkdir -p public/teste1
        mv * public/teste1/
        touch public/teste1/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy teste1 to GitHub Pages"
        git push origin teste1

    - name: Deploy teste2
      if: github.ref == 'refs/heads/teste2'
      run: |
        mkdir -p public/teste2
        mv * public/teste2/
        touch public/teste2/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy teste2 to GitHub Pages"
        git push origin teste2
