name: Deploy to GitHub Pages

on:
  push:
    branches:
      - grupoM1
      - grupoM2
      - grupoM3
      ##################
      - teste1
      - teste2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Deploy grupoM1
      if: github.ref == 'refs/heads/grupoM1'
      run: |
        mkdir -p public/grupoM1
        mv * public/grupoM1/
        touch public/grupoM1/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy grupoM1 to GitHub Pages"
        git push origin grupoM1

    - name: Deploy grupoM2
      if: github.ref == 'refs/heads/grupoM2'
      run: |
        mkdir -p public/grupoM2
        mv * public/grupoM2/
        touch public/grupoM2/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy grupoM2 to GitHub Pages"
        git push origin grupoM2

    - name: Deploy grupoM3
      if: github.ref == 'refs/heads/grupoM3'
      run: |
        mkdir -p public/grupoM3
        mv * public/grupoM3/
        touch public/grupoM3/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy grupoM3 to GitHub Pages"
        git push origin grupoM3
        
##################################################################################################
    - name: Deploy teste1
      if: github.ref == 'refs/heads/teste1'
      run: |
        mkdir -p public/teste1
        mv * public/teste1/
        touch public/teste1/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy teste1 to GitHub Pages"
        git push origin teste1

    - name: Deploy teste2
      if: github.ref == 'refs/heads/teste2'
      run: |
        mkdir -p public/teste2
        mv * public/teste2/
        touch public/teste2/.nojekyll
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy teste2 to GitHub Pages"
        git push origin teste2
