name: Publicar diretório work no GitHub Pages

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Verificar se a branch gh-pages existe
        run: |
          if ! git show-ref --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Inicializando a branch gh-pages"
            git push origin gh-pages
          else
            git fetch origin gh-pages
            git checkout gh-pages
            git reset --hard origin/gh-pages
          fi

      - name: Publicar no GitHub Pages
        run: |
          git worktree add ../gh-pages gh-pages
          rm -rf ../gh-pages/public/$BRANCH_NAME/work/*
          cp -r public/$BRANCH_NAME/work/* ../gh-pages/public/$BRANCH_NAME/work/
          cd ../gh-pages
          git add public/$BRANCH_NAME/work/
          git commit -m "Publicação automática do diretório work para $BRANCH_NAME"
          git pull --rebase origin gh-pages  # Sincroniza com as mudanças remotas
          git push origin gh-pages
